name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: coverage

      - name: Run SonarCloud analysis
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: sonar
